[wokwi]
version = 1
gdbServerPort = 3333
elf = "usbkwa/build/esp32.esp32.esp32s3usbotg/usbkwa.ino.elf"
firmware = "usbkwa/build/esp32.esp32.esp32s3usbotg/usbkwa.ino.elf"

#https://kgithub.com/wokwi/wokwi-boards/blob/main/boards/esp32-s3-devkitc-1/board.json